[workspace]
authors = ["Mridul Seth <git@mriduls.com>"]
channels = ["conda-forge"]
name = "pandemic-voici"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
ghbuild = "voici build --contents notebooks --output-dir dist"

[dependencies]
voici = ">=0.8.0,<0.9"
python = "3.11.*"
